require("nvim-treesitter.configs").setup {
    -- ensure_installed = "all",
    ensure_installed = {
        "css",
        "dockerfile",
        "fortran",
        "html",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "python",
        "regex",
        "rust",
        "toml",
        "typescript",
        "yaml",
    },
    ignore_install = {},
    highlight = {
        enable = true,
        disable = {},
        additional_vim_regex_highlighting = false,
    },
}
