context.modules = [
  {   name = libpipewire-module-loopback
      args = {
          node.name = "CallRecorder"
          node.description = "Call Recorder"
          capture.props = {
              media.class = "Audio/Sink"
          }
          playback.props = {
              media.class = "Audio/Source"
              node.name = "CallRecorderOutput"
              node.description = "Call Recorder Output"
          }
      }
  }
]
